apiVersion: v1
appVersion: "1.0"
version: 1.0.39
description: Helm chart for deploying Sematext Agent and Logagent to Kubernetes
keywords:
  - sematext
  - observability
  - monitoring
  - logging
  - containers
  - ebpf
home: https://sematext.com/cloud
icon: https://cdn.sematext.com/octi-square-logo.png
maintainers:
  - name: Rishabh Shah
    email: rishabh.shah@sematext.com
name: sematext-agent
